
export const NOTIFIER_SPRING_CONFIG = {
	damping: 25,
	stiffness: 400,
	mass: 0.5,
};

// NOTIFIER STACKING CONFIG
export const STACK_OFFSET = 8; // NOTIFIER STACKING OFFSET
export const STACK_SCALE_FACTOR = 0.95; // NOTIFIER STACKING SCALE FACTOR
export const MAX_VISIBLE_NOTIFICATIONS = 3; // NOTIFIER STACKING MAX VISIBLE NOTIFICATIONS